required:
- loser
- pathetic
- cringe
- embarrassing
- nobody
- weakling
- trash
- idiot
- fool
- moron
- clown
- dork
- nerd
- sucker
- chump
- dipshit
- loserface
- dumbass
- shithead
- piss-ant
- goofball
- numbskull
- halfwit
- doofus
- twit
- asshat
- butthole
- douchebag
- fuckwit
- jackass
- knucklehead
- lamebrain
- nitwit
- pinhead
- schmuck
- dweeb
- freak
- goon
- jerk
- loserboy
- muppet
- numpty
- prat
- schmucko
- twat
- scumbag
- prick
- wanker
- tosser
- bellend
- cocksucker
- shitstain
- pisshead
- dickhead
- bollocks
- loserbot
- patheticloser
- cringelord
- embarrassment
- nobodyknows
- weakass
- trashbag
- idiotboy
- foolproof
- moronmove
- asswipe
- butthurt
- crybaby
- pansy
- knobhead
- cry-me-a-river
- pansy-ass
- lowlife
- jerkoff
- tool
- bonehead
- airhead
- freakshow
- hater
- craphead
- wannabe
- scrub
- pipsqueak
- weirdo
- sissy
- beta
- toolbag
- salty
- pwned
- beta-boy
- wankstain
- tosspot
- pest
- slob
- creep
- punk
- zero
- wuss
- dimwit
- scum-sucker
- bastard
- loser-vibes
- pathetic-worm
- cringe-king
- embarrassment-factory
- nobody-special
- weak-sauce
- trash-panda
- idiot-box
- fool-gold
- moron-magnet
- blockhead
- dumbshit
- wussbag
- assclown
- retard
- cryloser
- pansyass
- sniveler
- whimperer
- dolt
- meathead
- fumblebrain
- gullible-goof
- misfit-mook
- punchbag
- easy-target
- whip-boy
- scapegoat
- hate-magnet
- bully-bait
- pity-case
- mock-meat
- gossip-fodder
- beta-male
- punchline
- squirt
- misfit
- tough-guy-pretend
- victim-vibes
- easy-mark
- target-dummy
- harass-bait
- stalker-magnet
- troll-feast
- abuse-sponge
- attack-magnet
- bully-fodder
- victim-bait
- stalk-prey
- troll-target
- whinebag
- fumble-fool
- blunder-butt
- snivel-stick
- gripe-goblin
- moan-muppet
- sob-sack
- wail-worm
- weak-link
- punching-bag
- harass-target
- witless-wonder
- gossip-goblin
- sniveling-rat
- mockery-magnet
- hate-bait
- derision-doll
- torment-toy
- shame-shield
- snowflake
- tryhard
- noob
- nuisance
- mock-bait
- harass-prey
- attack-dummy
- total-loser
- harass-me
- brain-fart
- puke-worthy
- failure-factory
- jealous-jerk
- nitwit-nuisance
- obsession-object
- gossip-grub
- flop-sweat
- rage-bait
- snark-target
- beta-cuck
- snivel-nose
- gutless-worm
- fumble-freak
- harass-meat
- zero-chance
- mock-target
- total-failure
- harassment-hound
optional:
- lame
- failure
- worthless
- joke
- desperate
- zero
- has-been
- reject
- outcast
- wimp
- coward
- loser-wannabe
- pity-party
- sob-story
- fake-tough
- paper-tiger
- empty-threat
- keyboard-warrior
- armchair-critic
- backstabber
- snitch
- tattletale
- crybaby
- whiner
- moaner
- victim-card
- attention-seeker
- drama-queen
- poser
- fraud
- gutless
- spineless
- yellow-belly
- chicken-shit
- bootlicker
- rat-fink
- back-pedaler
- excuse-maker
- blame-shifter
- fragile-ego
- thin-skinned
- over-sensitive
- whine-machine
- tears-on-tap
- pouty-face
- sulk-fest
- mope-around
- gloom-goblin
- doom-sayer
- neg-head
- buzzkill
- party-pooper
- vibe-killer
- mood-ruiner
- fun-sucker
- beta-male
- cuckold
- deadweight
- embarrassment
- flop
- grifter
- hack
- imposter
- jerkoff
- know-nothing
- lowlife
- misfit
- noob
- oddball
- pushover
- quitter
- retard
- scum
- sellout
- shyster
- slacker
- tool
- underdog
- useless
- villain
- airhead
- babbler
- blowhard
- blunderer
- boob
- braggart
- bungler
- cheater
- choker
- clownshoe
- cry-me-a-river
- delusional
- dimwit
- ditz
- doormat
- dunce
- egotist
- empty-headed
- fumble-fingers
- gawk
- goof-off
- gullible
- half-baked
- hot-air-balloon
- hypocrite
- inferior
- mockery
- despised
- bullied
- harassed
- tormented
- ridiculed
- humiliated
- shamed
- targeted
- stalked
- baited
- trolled
- flamed
- roasted
- owned
- pwned
- schooled
- clowned
- dissed
- burned
- zapped
- slammed
- trashed
- totalflop
- uselesspiece
- bigjoke
- hopelesscase
- absolutezero
- washedup
- socialreject
- totalwimp
- scaredycat
- wannabefailure
- pitycase
- whinefest
- pretendbrave
- allbark
- nothreat
- onlinebully
- couchpotato
- traitor
- informer
- babycry
- complainer
- griper
- victimplay
- spotlightchaser
- dramaking
- bitch-boy
- ego-trip
- flop-sweat
- grudge-holder
- haterade
- insecure-clown
- jealous-rage
- knee-jerk
- lowlife-scum
- noob-mistake
- overrated
- pity-case
- quitters-club
- resentful
- salt-mine
- scapegoat
- shade-thrower
- sore-loser
- toxic-vibe
- underachiever
- vanity-fair
- weak-sauce
- insecure
- karma-dodger
- obsessed
- petty-thief
- rage-quit
- salty
- stalker-vibes
- toxic-spill
- underdog-fail
- vanity-project
- delusion-den
- ego-deflater
- fake-brave
- jealous-jerk
- lowlife-lurker
- misfit-mess
- noob-nightmare
- obsession-freak
- petty-punk
- quit-quitter
- rage-baiter
- salt-shaker
- stalker-vibe
- troll-bait
- vanity-victim
- whine-whore
- total-flop
- epic-fail
- zero-chance
- dream-killer
- hope-crusher
- vibe-assassin
- fun-sponge
- joy-thief
- hype-buster
- gossip-monger
- rumor-spreader
- lie-peddler
- truth-twister
- fact-faker
- story-spinner
- tale-weaver
- fibber
- deceiver
- manipulator
- schemer
- plotter
- con-artist
- hustler
- slowpoke
- dawdler
- total-flunk
- ego-buster
- flop-artist
- hype-dropper
- buzz-killer
- vibe-ruiner
- mood-spoiler
- smirk-smother
- gloat-grabber
- smug-buster
- brag-breaker
- boast-buster
- flex-failer
- strut-stumbler
- pose-crusher
- front-faller
- act-dodger
- bluff-caller
- hollow-hype
- fake-flex
- phony-front
- sham-show
- bogus-boast
- lame-lie
- weak-whisper
- broken-record
- canned-laughter
- card-carrying-loser
- clown-shoes
- copycat-cretin
- cornered-rat
- couch-potato-critic
- crackpot
- credibility-zero
- crocodile-tears
- cut-rate
- dead-weight
- delusional-dork
- desperation-move
- dime-store-drama
- dirtbag
- disaster-area
- ditch-digger
- downer
- drama-llama
- dud
- mock-target
- harass-bait
- insult-magnet
- shame-sponge
- ridicule-rag
- taunt-toy
- bully-bait
- slander-sink
- gossip-grub
- rumor-rat
- smear-slug
- defame-dud
- troll-trap
- hate-hound
- bash-bot
- flame-fodder
- roast-runt
- dig-dolt
- jab-junkie
- snide-snake
- sarcasm-slap
- barb-bum
- cut-clown
- zinger-zilch
- quip-quitter
- zero-charm
- social-leper
- awkward-duck
- sweat-rag
- lame-duck
- burden-bearer
- drag-anchor
- sinker-stone
- flounder-fish
- gasp-clown
- stutter-bug
- blush-bomb
- fumble-fool
- trip-hazard
- stumble-bum
- gawk-stare
- drool-drip
- slobber-jaw
- mumble-mouth
- whimper-wimp
- snivel-snot
- cowardly-lion
- fake-news
- glory-hog
- hollow-victory
- know-it-all
- narcissist
- quit-now
- self-pity
- tantrum-thrower
- toxic-waste
- whistle-blower
- yap-trap
- ego-bubble
- loser-vibes
- mock-victim
- no-spine
- overreactor
- petty-fight
- scapegoat-hunter
- under-dogged
- whine-wagon
- attention-whore
- butterfingers
- cape-crusader
- choke-artist
- copycat
- couch-potato
- daydreamer
- dunce-cap
- egghead
- facepalm
- faint-hearted
- fence-sitter
- foot-in-mouth
- snowflake
- triggered
- safe-space
- virtue-signal
- white-knight
- simp
- incel
- soy-boy
- fragile
- delicate
- oversensitive
- petty
- vindictive
- spiteful
- malicious
- nasty
- vile
- repulsive
- disgusting
- revolting
- abominable
- loathsome
- despicable
- contemptible
- sidekick
- flunky
- toady
- sycophant
- liar
- thief
- plagiarist
- mimic
- echo
- parrot
- sheep
- follower
- trend-chaser
- bandwagon
- leech
- parasite
- freeloader
- moocher
- sponger
- beggar
- scrounger
- handout-hunter
- welfare-queen
- lazy-bones
- deadbeat
- ego-deflated
- punchline
- side-show
- blunder-boss
- gaffe-machine
- slip-up-specialist
- oops-artist
- fail-factory
- mockery-magnet
- ridicule-rider
- taunt-target
- jeer-junkie
- sneer-subject
- gloat-goal
- shame-shield
- humiliation-hunter
- derision-doll
- scorn-sponge
- contempt-collector
- disdain-dummy
- belittle-bait
- degrade-dude
- insult-incubator
- total-flops
- punchline-waiting
- sneer-sucker
- deride-dud
- belittle-bum
- scoff-slob
- gibe-goof
- jibe-jerk
- rib-runt
- tease-turd
- heckle-hack
- bait-buffoon
- prod-pest
- poke-punk
- prodigy-of-piss
- harass-hobo
- torment-twit
- victim-vibe
- harassment-hound
- ice-cold
- jelly-spine
- no-account
- odd-ball
- runt
- small-fry
- softie
- stink-bug
- under-dog
- vanilla
- washout
- zero-hour
- cred-killer
- reputation-ruiner
- social-sink
- peer-reject
- group-outcast
- clique-bane
- ally-betrayer
- trust-breaker
- petty-hater
- vendetta-holder
- grudge-nurse
- spite-machine
- malice-peddler
- hate-spewer
- troll-master
- bait-dropper
- flame-stoker
- chaos-creator
- discord-sower
- candy-ass
- douche-nozzle
- fakersville
- gawkward
- milquetoast
- fraidy-cat
- sissy
- pansy
- mama-boy
- butthurt
- seething
- raging
- meltdown-mode
- hissy-fit
- petty-bitch
- venom-spitter
- flame-warrior
- dox-threat
- swarm-attack
- pile-on
- cancel-mob
- thot-hunter
- incel-vibes
- flame-bait
- noob-tear
- cry-more
- ownage
- rekt-life
- harass-mode
- spam-attack
- swarm-hate
- shame-game
- guilt-trip
- mind-fuck
- gaslight-pro
- broken-toy
- defeatist
- hater-vibes
- jealous-runt
- kicked-puppy
- misfit-reject
- needy-clinger
- overrated-fool
- quitter-king
- resentful-weasel
- scaredy-cat
- self-pity-king
- toxic-sponge
- underdog-fraud
- vanity-case
- side-splitter
- gut-buster
- humiliation-hog
- derision-dummy
- sarcasm-sink
- irony-idiot
- satire-slap
- banter-bait
- jibe-junkie
- ribbing-reject
- tease-toy
- snark-sucker
- jab-jester
- poke-patsy
- prod-punk
- pissweak
- gutless-wonder
- sniveler
- boot-licker
- rat-bastard
- weasel-words
- coward-punch
- whimpering
- teary-eyed
- snot-nosed
- pissy-mood
- whine-bottle
- fragile-pride
- ego-bruise
- sensitivity-overload
- drama-monger
- victim-mode
- pity-plays
- sob-fest
- mopey-git
- gripe-session
- hate-bait
- troll-target
- bash-buddy
- insult-inciter
- roast-ready
- dig-digger
- slam-specialist
- taunt-taker
- gibe-goat
- ribbing-recipient
- deride-dummy
- scoff-scapegoat
- mock-meat
- harass-honey
- harass-hack
- prey-pathetic
- stalker-scorn
- campaign-clown
- attack-ape
- personal-poke
- red-pill
- blue-pill
- coping-mechanism
- delusion
- fantasy-land
- reality-check
- psycho
- stalker
- harasser
- flame-war
- dox-drop
- flake-out
- bailout
- cop-out
- whine-bag
- complaint-factory
- gripe-machine
- fault-finder
- naysayer
- pessimist
- wet-blanket
- killjoy
- spoilsport
- grump
- sourpuss
- delusion-station
- fake-it-till-you-make-it
- mama's-boy
- no-life
- obsessed-fanboy
- quit-while-ahead
- thirst-trap
- under-dog-bark
- sidekick-fail
- backup-loser
- shadow-dweller
- echo-chamber
- mimic-mess
- copycat-crap
- bandwagon-jumper
- hype-victim
- viral-fail
- meme-misfit
- trend-trash
- fame-fumble
- spotlight-dodge
- crowd-pleaser-fail
- groupie-gone-wrong
- pack-follower
- lone-flunk
- solo-sink
- team-dragger
- crew-curse
- squad-sabotage
- ally-idiot
- partner-pest
- buddy-bust
- pal-problem
- cry-me-river
- delusional-dreamer
- hypocrite-alert
- lame-excuse
- misfit-toy
- obsessed-fan
- salty-tears
- ego-popper
- whine-bait
- snivel-fest
- pity-plug
- drama-drip
- threat-bluff
- coward-call
- snitch-slime
- rat-race
- backstab-blade
- tattle-turd
- cry-fest
- moan-mess
- seek-spotlight
- queen-drama
- pose-fake
- fraud-alert
- gut-punch
- spine-miss
- belly-yellow
- shit-chicken
- lick-boot
- fink-rat
- pedal-back
- make-excuse
- dropout
- loner
- hot-air
- bluff-artist
- gripe-master
- sensitivity-freak
- complaint-king
- mood-killer
- doom-cloud
- negativity-nest
- whimper-worm
- sulky-slug
- grouch-goblin
- resent-rat
- punchline-daily
- brag-fail
- hype-bust
- cred-zero
- meme-fodder
- roast-bait
- buzz-kill
- petty-poke
- snark-target
- gossip-fodder
- rival-bait
- hater-magnet
- troll-food
- dig-deep
- jab-quick
- mock-fest
- taunt-loop
- harass-hive
- gaffe-guru
- oops-master
- ridicule-radar
- jeer-jester
- ribbing-rat
- poke-fun-puppet
- banter-butt
- quip-quarry
- blunder-boy
- fumble-freak
- oops-king
- derp-dude
- goof-guru
- silly-sap
- ditz-dynamo
- klutz-kingpin
- bungle-boss
- hash-head
- muddle-man
- tangle-twit
- snarl-sucker
- knot-ninny
- mess-monger
- slacker-king
- downer-dude
- rage-machine
- baiter-pro
- flame-thrower
- insult-artist
- roast-king
- savage-mode
- cut-throat
- screw-up
- harass-hound
- troll-king
- bait-master
- flame-fanatic
- dox-demon
- spam-savage
- roast-ringleader
- taunt-tyrant
- mock-monarch
- bully-boss
- hate-hustler
- snark-slinger
- dig-dominator
- insult-instigator
- provoke-pro
- agitate-ace
- rile-ruler
- neckbeard
- manlet
- chad-wannabe
- looks-maxxer
- rope-fuel
- blackpill
- cope-meister
- seethe-post
- melt-down
- tilt-mode
- own-goal
- self-own
- gaffe-king
- slip-up
- face-plant
- hype-killer
- laugh-blocker
- smirk-stealer
- giggle-grabber
- chuckle-choker
- snicker-stopper
- guffaw-gobbler
- harsh-reality
- cold-truth
- brutal-fact
- stark-reminder
- painful-truth
- ugly-reality
- harsh-light
- cold-shower
- wake-up-call
- ego-puncture
- pride-deflater
- confidence-crusher
- self-esteem-smasher
- dignity-destroyer
- failure-mode
- worthless-slob
- joke-clown
- desperate-cling
- has-been-hero
- reject-pile
- outcast-vibe
- wimp-out
- loser-dream
- pity-bait
- paper-hero
- empty-bluff
- keyboard-tough
- armchair-bully
- backstab-artist
- snitch-line
- tattle-tale
- whine-wheel
- moan-fest
- victim-play
- attention-grab
- drama-king
- poser-act
- spineless-jelly
- yellow-streak
- attack-dog
- snide-jab
- ruthless-taunt
- personal-slam
- despair-monger
- gripe-guru
- sob-squad
- pity-ploy
- fake-victim
- sob-sister
- moan-master
- doom-dweller
- pess-pest
- gloomy-gus
- scaredy-pants
- weak-kneed
- feeble-minded
- brain-fart
- scatterbrain
- nitwit
- botched-job
- bust
- roast-meat
- flame-out
- nitpicker
- rant-rabbit
- beef-builder
- vendetta-vibe
- spite-spitter
- complainant
- kvetcher
- bellyacher
- grumbler
- malcontent
- disgruntled
- bitter-pill
- sour-grapes
- jealous-type
- envy-monger
- petty-betty
- attack-dummy
- verbal-punching-bag
- insult-sponge
- derision-target
- shame-collector
- taunt-trap
- gossip-goat
- sarcasm-slave
- barb-bearer
- dig-dweller
- slur-soaker
- troll-toy
- bait-ball
- hassle-hog
- victim-mentality
- entitlement-king
- block-button
- mute-mode
- scroll-past
- ignore-fest
- fit-pitcher
- meltdown-master
- hysteria-hype
- panic-button
- freak-out
- gossip-grinder
- bailout-king
- excuse-factory
- teardrop
- snivel-nose
- pity-plunger
- backbiter
- slander-slinger
- libel-lizard
- flame-fanner
- vitriol-vendor
- beggar-king
- pity-plunder
- sob-swindler
- drama-leech
- poser-punk
- fraud-freak
- gutless-goblin
- spineless-snake
- yellow-jerk
- chicken-liver
- boot-lick
- back-stabber
- excuse-freak
- blame-game
- fragile-fool
- thin-skinned-twit
- over-react
- whine-factory
- tear-jerker
- pout-master
- sulk-king
- snivel-bot
- moan-monger
- sob-slinger
- teardrop-titan
- wallow-wizard
- fret-fiend
- bitch-blaster
- complaint-clown
- victim-vortex
- hissy-hustler
- tantrum-tosser
- beef-brewer
- rant-rat
- kvetch-king
- bellyache-bard
- gripe-giant
- whimper-wraith
- laugh-riot
- torment-titan
- harass-hero
- attack-ace
- bash-boss
- insult-emperor
- deride-dominator
- sneer-sovereign
- jeer-juggernaut
- scoff-supreme
- gloat-guru
- victory-vulture
- triumph-troll
- dominance-demon
- superiority-snake
- bully-baron
- scoff-sucker
- ribbing-rube
- stalker-slob
- troll-turd
- bait-biter
- dox-dolt
- swarm-scum
- pile-on-pest
- gang-up-goon
- mob-moron
- sniveling-rat
- whimpering-pup
- threat-bluffer
- harass-dodger
- attack-avoider
- easy-target
- soft-mark
- vulnerable-spot
- harassment-magnet
- attack-victim
- personal-foe
- targeted-prey
- campaign-victim
- relentless-mark
- persistent-target
- hate-focus
- scorn-receiver
- mockery-subject
- insult-recipient
- tremble-legs
- fear-monger
- hidey-hole
- sneak-attack
- whisper-coward
- shadow-stalker
- petty-vandal
- insult-factory
- mock-master
- taunt-king
- bully-club
- stalker-mode
- cancel-cry
- fragile-soul
- drama-dynamo
- coward-core
- belly-acher
- punching-bag
- whine-bucket
- attack-magnet
- bully-fodder
- punchbag
- easy-mark
- target-practice
- stalker-magnet
- troll-fuel
- fragile-psyche
